MY First NoteBook

In [7]:
roll = 1
height = 5.5
name = 'Parth'
print("Roll is :",roll)
print('Height is :', height)
print('Name is :', name)

Roll is : 1
Height is : 5.5
Name is : Parth


In [12]:
l=list('HELLO')

'first={0[0]}, third={0[2]}'.format(l)

'first=H, third=L'

In [23]:
def secret(s):

   i = 0

   result = ''

   while s[i].isdigit():

      result = result + s[i]

      i = i+1

   return result
secret('123')

IndexError: string index out of range

In [33]:
a={'B':5,'A':9,'C':7}

b=sorted(a)

In [8]:
print(type(roll))
print(type(height))
print(type(name))

<class 'int'>
<class 'float'>
<class 'str'>


In [36]:
a={"a":1,"b":2,"c":3}

d=[zip(a.values(),a.keys())]
b=dict(zip(a.values(),a.keys()))
print(d)
b

{1: 'a', 2: 'b', 3: 'c'}

In [5]:
courses == 3

NameError: name 'courses' is not defined

In [10]:
int(72.5)

72

In [11]:
x = 12 / 3
x

4.0

In [12]:
try:

    list = 5 * [0]

    x = list[5]

    print("Done")

except IndexError: 

    print("Index out of bound")

Index out of bound


In [1]:
num1 = 10

num2 = 0

try:

    result = num1 / num2

    print(result)

    num2 -= 1

except:

    print("Divide by zero !")

Divide by zero !


In [14]:
for i in range(1, 6 + 1):

    for j in range(6, 0, -1):

       print(j if j <= i else " ", end = " ")

    print()

          1 
        2 1 
      3 2 1 
    4 3 2 1 
  5 4 3 2 1 
6 5 4 3 2 1 


In [15]:
l=list('HELLO')

'first={0[0]}, third={0[2]}'.format(l)

TypeError: 'list' object is not callable

In [18]:
1st_name=1

SyntaxError: invalid syntax (<ipython-input-18-90525cdf44b3>, line 1)

In [24]:
age1 = input("How old are you? ")

age2 = input("How old is your best friend? ")
x=int(age1)
y=int(age2)
print(str(x+y))
print(str(int(age1+age2))) 
print(int(age1)+int(age2))
print(age1 + age2)
print(type(x+y))

How old are you? 20
How old is your best friend? 23
43
2023
43
2023
<class 'int'>


In [4]:
data = 'From stephen.marqaurd@uct.ac.za Sat Jan 5'
print(data.find('@'))
print(data.find(' ',6))
print(data[22:31])

21
31
uct.ac.za


In [13]:
data1= ' X-DPSM confidence:0.59432'
x=float(data1[data1.find(':')+1:])
print(type(x))

<class 'float'>


In [27]:
print("Hi this is {} from hyderabad are you {}".format('saiprasad','there'))

Hi this is saiprasad from hyderabad are you there


In [31]:
print("Hi this is %s from hyderabad are you %s" %('saiprasad','there'))

Hi this is saiprasad from hyderabad are you there


In [29]:
print("Hi this is %s class and we are studying %s data structure" %('python', 'strings'))

Hi this is python class and we are studying strings data structure


In [1]:
names=['Raju','Ravi','Priya','Ravi','Raju', 'Raju', 'Sri']

In [2]:
counts=dict()
for i in names:
    counts[i]=counts.get(i,0)+1
print(counts)

{'Raju': 3, 'Ravi': 2, 'Priya': 1, 'Sri': 1}


In [4]:
text ="the clown ran after the car and the car ran into the tent and the tent fell on the clown and the car"

In [6]:
counts1=dict()
text_lst=text.split(" ")
for i in text_lst:
    counts1[i]=counts1.get(i,0)+1
print(counts1)

{'the': 7, 'clown': 2, 'ran': 2, 'after': 1, 'car': 3, 'and': 3, 'into': 1, 'tent': 2, 'fell': 1, 'on': 1}


In [13]:
for i,j in counts1.items():
    if j==max(counts1.values()):
        print("Max key is:", i)

Max key is: the


In [12]:
fruits_to_color = {'watermelon':'green','peach':'orange','cherry':'red','banana':'yellow','orange':'orange'}
invert_dict={}
for i in fruits_to_color:
    if fruits_to_color[i] not in invert_dict:
        invert_dict[fruits_to_color[i]]=[i]
    else:
        invert_dict[fruits_to_color[i]].append(i)
print(invert_dict)

{'green': ['watermelon'], 'orange': ['peach', 'orange'], 'red': ['cherry'], 'yellow': ['banana']}


In [23]:
l2=[i for i in range(50) if i%2==0 else "odd"]
l2

SyntaxError: invalid syntax (<ipython-input-23-8238e7f1ac8b>, line 1)

In [27]:
fruits = ['apple','banana','cherry','duke']
for i in fruits:
    print(i[0][0])


a
b
c
d


In [33]:
l3=[i[0].upper() for i in fruits]
l3

['A', 'B', 'C', 'D']

In [1]:
def sq_num(x):
    return(x**2)

In [6]:
lst_1 = [1,2,3,4,5]
f=list(map(sq_num,lst_1))
print(f)
print(lst_1)

[1, 4, 9, 16, 25]
[1, 2, 3, 4, 5]


In [11]:
xy=[]
for i in map(lambda x:x**2,lst_1):
    xy[]=i
print(xy)

25


In [52]:
orders = [[1,(100,500.50,450)],[2,(200,300.75,450.50)],[3,(400,350.50,650.50)]]
orders[1]

[2, (200, 300.75, 450.5)]

In [22]:
from functools import reduce
list(map(lambda x:[x[0]], orders))

[[1], [2], [3]]

In [29]:
[reduce(lambda a,b:a+b, orders[0][1])]

[1050.5]

In [40]:
x=lambda x:[x[0]] + [reduce(lambda a,b:a+b, x[1])]
x

<function __main__.<lambda>(x)>

In [50]:
Total = list(map(lambda x:[x[0]] + [reduce(lambda a,b:a+b, x[1])], orders))
print(Total)

[[1, 1050.5], [2, 951.25], [3, 1401.0]]


In [41]:
enu_lst=['Hi','Hello','mast']
print(list(enumerate(enu_lst, start=5)))

[(5, 'Hi'), (6, 'Hello'), (7, 'mast')]


In [45]:
z1=['Hi','there','guys']
z2=[10,20,30]
z3=['sai','shyam','car']
print(list(zip(z1,z2,z3)))

[('Hi', 10, 'sai'), ('there', 20, 'shyam'), ('guys', 30, 'car')]


In [65]:
s1="bad@string"
s1.find('c')

-1

In [121]:
listt=[20,10,30,'sam']
listt

[20, 10, 30, 'sam']

In [98]:
import pandas as pd

In [100]:
ser = pd.Series([100,200,300,400,500],['tom','ram','rao','cat','dash'])
ser

tom     100
ram     200
rao     300
cat     400
dash    500
dtype: int64

In [112]:
ser.loc[['tom','rao']]

tom    100
rao    300
dtype: int64

In [113]:
ser.iloc[2:5]

rao     300
cat     400
dash    500
dtype: int64

In [117]:
s=pd.Series()
s

Series([], dtype: float64)

In [119]:
s=ser*2
s

tom      200
ram      400
rao      600
cat      800
dash    1000
dtype: int64

In [120]:
arr=np.array([1,2,3,4])
arr.shape

(4,)

In [141]:
np.random.seed(5)
ex5=np.random.rand(1,10)
print(ex5)

[[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386
  0.76590786 0.51841799 0.2968005  0.18772123]]


In [130]:
a1=np.random.uniform(1,10,(2,2))
print(a1)

[[1.72667142 7.64596267]
 [4.97178301 2.42478881]]


In [140]:
lit =np.array([-0.51733692,0.48813676, -0.88147002 , 1.12901958 ,0.68026197])
lit.mean()

0.17972227400000002

In [148]:
np.random.seed(5)

In [149]:
dice=np.random.randint(1,7,20)
dice

array([4, 6, 1, 2, 1, 5, 4, 1, 1, 5, 2, 6, 1, 4, 5, 6, 4, 2, 5, 6])

In [4]:
import pandas as pd

In [10]:
d= {'one': pd.Series([100,200,300,400],['bam','cam','dam','fan']),
     'two': pd.Series([110.0,120.0,130.0],['bam','cam','dam'])}
d

{'one': bam    100
 cam    200
 dam    300
 fan    400
 dtype: int64, 'two': bam    110.0
 cam    120.0
 dam    130.0
 dtype: float64}

In [11]:
df = pd.DataFrame(d)
df

one    two
bam  100  110.0
cam  200  120.0
dam  300  130.0
fan  400    NaN

In [19]:
pd.DataFrame(d, index=['bam','dam'])

one    two
bam  100  110.0
dam  300  130.0

In [21]:
data = [{'alice':1,"joe":2},{'jam':10,'scam':100,"doom":1000}]

In [23]:
pd.DataFrame(data)

alice    doom   jam  joe   scam
0    1.0     NaN   NaN  2.0    NaN
1    NaN  1000.0  10.0  NaN  100.0

In [24]:
pd.DataFrame(data, index=['orange','red'])

alice    doom   jam  joe   scam
orange    1.0     NaN   NaN  2.0    NaN
red       NaN  1000.0  10.0  NaN  100.0

In [14]:
l1=[1,2,3]

l2=[4,5,6]

l3=[7,8,9]

#for x, y, z in zip(l1, l2, l3):

#	print(x, y, z)

print(list(zip(l1, l2, l3)))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]


In [15]:
import numpy as np

In [19]:
A = np.array([[1,2,3]])

B = np.array([[1,1,1], [2,2,2], [3,3,3]])

print(A)
print(B)
print(B+A)

[[1 2 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]
