<h2>Introduction to numpy</h2>

<h4>
Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.</h4>
<h4>Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.</h4>

<h4>The key features of numpy are:</h4>

<h4>ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient. </h4>
<h4>There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).</h4>
<h4>Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.</h4>
<h4>Vectorization: enables numeric operations on ndarrays.</h4>

In [2]:
import numpy as np

<h3>Creating 1-D array</h3>

In [4]:
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [5]:
#test the shape of the array we just created, it should have just one dimension (rank 1) 
print(arr.shape)

(5,)


In [6]:
print(arr[0],arr[1],arr[2])

1 2 3


In [7]:
arr[0]=8
print(arr)
#ndarrays are mutable

[8 2 3 4 5]


In [8]:
arr1=np.array([1,2,2.6,'c'])
print(arr1)
#np.array are homogenous

['1' '2' '2.6' 'c']


<h2>How to create a Rank 2 numpy array:</h2>
    <h4>A rank 2 nd arry is one with two dimensions. Notice the format below [[row],[row]]</h4>

In [19]:
arr_twod = np.array([[11,12,13,88],[21,22,23,44]])
#if lists are not equal it will be converted to 1D list
print(arr_twod)
print(arr_twod.shape)
print(arr_twod[0][2])

[[11 12 13 88]
 [21 22 23 44]]
(2, 4)
13


In [16]:
import matplotlib.pyplot as plt

In [27]:
np.random.seed(10)
ex5=np.random.rand(10)
print(ex5)

a1=np.random.uniform(1,10,(2,2))
print(a1)

ex6 =np.random.randn(5)
print(ex6)

a2=np.random.normal(0,3,(2,3))
print(a2)

exp7 = np.random.randint(1,100,10)
print(exp7)

ex8 = np.random.randint(1,100,(3,3))
print(ex8)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]
[[4.77275063 7.1669755 ]
 [2.84007025 8.90305693]]
[ 1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944]
[[-3.2996738  -0.51728462 -2.63357525]
 [ 0.12664124  1.74844564 -3.30185753]]
[77 27 53 81 42 83 16 65 69 26]
[[99 88  8]
 [27 26 23]
 [10 68 24]]


<h4>Exercise 1: Generate list of 20 random samples for a dice throw</h4>

In [4]:
dice_samples =np.random.randint(1,7,20)
dice_samples

array([3, 1, 1, 1, 3, 1, 5, 5, 2, 1, 3, 5, 1, 6, 4, 6, 4, 3, 2, 2])

<h2>Basics of NumPy Arrays</h2>

<h3>1.Attributes of Array</h3>
<h4>Determining the size, shape, data type and dimensions of array</h4>

In [4]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
print('X1 array is : ' ,x1)
print('**********')
print('X2 array is : ')
print(x2)
print('**********')
print('X3 array is : ')
print(x3)

X1 array is :  [9 3 8 9 2 0]
**********
X2 array is : 
[[0 0 9 8]
 [8 5 5 6]
 [5 7 3 8]]
**********
X3 array is : 
[[[0 0 1 7 6]
  [8 7 3 2 9]
  [1 3 0 2 4]
  [2 9 4 0 4]]

 [[6 5 8 2 5]
  [3 0 0 1 9]
  [1 7 6 1 9]
  [8 1 1 9 0]]

 [[9 6 8 6 3]
  [4 7 3 2 9]
  [9 3 5 3 7]
  [2 8 8 8 6]]]


In [6]:
print("dimension of x1: ",x1.ndim)
print("Shape of x1 :",x1.shape)
print("size of x1:",x1.size)
print("data type of x1 :",x1.dtype)

dimension of x1:  1
Shape of x1 : (6,)
size of x1: 6
data type of x1 : int64


In [7]:
print("dimension of x2: ",x2.ndim)
print("Shape of x2 :",x2.shape)
print("size of x2:",x2.size)
print("data type of x2 :",x2.dtype)

dimension of x2:  2
Shape of x2 : (3, 4)
size of x2: 12
data type of x2 : int64


In [8]:
print("dimension of x3: ",x3.ndim)
print("Shape of x3 :",x3.shape)
print("size of x3:",x3.size)
print("data type of x3 :",x3.dtype)

dimension of x3:  3
Shape of x3 : (3, 4, 5)
size of x3: 60
data type of x3 : int64


<h3>Array Indexing</h3>

In [14]:
#Rank 2 array of shape (3,4)
p=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(p)
p.shape

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


(3, 4)

In [12]:
#Rank 2 array of shape (3,4) dtype='int32' or np.int32
p=np.array([[11,12,13,14.09],[21.45,22,23,24],[31,32,33.67,34]],dtype='int32')
print(p)
p.shape

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


(3, 4)

In [13]:
p=np.array([[11,12,13,14.09],[21.45,22,23,24],[31,32,33.67,34]],dtype=np.float)
print(p)
p.shape

[[11.   12.   13.   14.09]
 [21.45 22.   23.   24.  ]
 [31.   32.   33.67 34.  ]]


(3, 4)

<h3>Normal Indexing</h3>
<h4>We can use rows and cols index values to retrive any element</h4>

In [15]:
p[2,2],p[1,3]

(33, 24)

In [16]:
p[2,2]=50

In [17]:
p

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 50, 34]])

<h3>Slice Indexing</h3>

In [18]:
p_slice=p[0:2,0:2]
print(p_slice)
print(p_slice.shape)

[[11 12]
 [21 22]]
(2, 2)


In [19]:
print(p_slice[0,0],p_slice[1,1])

11 22


In [20]:
p_slice[0,1]=60
p_slice

array([[11, 60],
       [21, 22]])

In [23]:
#In basic indexing if we slice and change the value it will 
#reflect in orginal array too
p 

array([[11, 60, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 50, 34]])

In [24]:
a_slice=p[:2,1:3].copy()#create explicit copy
a_slice[0,0]=1000
print(p)
print(a_slice)

[[11 60 13 14]
 [21 22 23 24]
 [31 32 50 34]]
[[1000   13]
 [  22   23]]


<h4>Use both normal indexing and slice indexing</h4>

In [27]:
#create a rank 2 array of shape (3,4)
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [28]:
#using both integer scalar and slicing generates an array of lower rank
row_rank1 = an_array[1,:] #rank 1 view
print(row_rank1,row_rank1.shape) #notice only singe []

[21 22 23 24] (4,)


In [29]:
#slicing alone: generates an of same rank
row_rank2=an_array[1:2,:] #rank 2 view
print(row_rank2,row_rank2.shape) #notice the [[]]

[[21 22 23 24]] (1, 4)


In [30]:
#we can do the same thing for colums of an array:
print()
col_rank1 = an_array[:,1]
col_rank2 = an_array[:,1:2]

print(col_rank1,col_rank1.shape) #rank 1
print()
print(col_rank2,col_rank2.shape) #rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [43]:
#arbitary value means any value in an array
print(an_array[[[0,0],[2,2]],[[0,2],[0,2]]])

[[11 13]
 [31 33]]
