In [2]:
import numpy as np

<h3>Integer Indexing</h3>

In [2]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
y=x[[0,1,2],[0,1,0]] # selects elements from (0,0)(1,1)(2,0)
y

array([1, 5, 7])

In [4]:
print(y[0])
print(y[2])

1
7


In [7]:
y[1]=10 #change in y doesn't change in main matrix x
y

array([ 1, 10,  7])

In [8]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h4>Exercise: create 3x3 array and retrive corner elements</h4>

In [5]:
y = x[[0,0,2,2],[0,2,0,2]]
y

array([1, 3, 7, 9])

In [6]:
r = [0,0,2,2]
c = [0,2,0,2]
a = x[r,c]
print(a)

[1 3 7 9]


In [8]:
rows = np.array([[0,0],[2,2]])
print(rows)
print('*******')
cols = np.array([[0,2],[0,2]])
print(cols)
print('*******')
y = x[rows,cols]
print(y)

[[0 0]
 [2 2]]
*******
[[0 2]
 [0 2]]
*******
[[1 3]
 [7 9]]


<h3>Boolean Indexing</h3>

In [10]:
#create a 3x2 array
an_array = np.array([[11,12],[21,22],[31,32]])
an_array

array([[11, 12],
       [21, 22],
       [31, 32]])

In [11]:
#create a filter which will be boolean values for 
filter1 = an_array<15
filter1

array([[ True,  True],
       [False, False],
       [False, False]])

<h4>Notice that the filter is a same size ndarray as an_array which is filled 
Truw for each element whose corresponding element is an_array which is greater than 15 and false for 
those elements whose value is less than 15.</h4>

In [13]:
#we can now select just those elements which meet that criteria
result=an_array[filter1]
result

array([11, 12])

In [14]:
result[0]

11

In [15]:
result[0]=100

In [16]:
result

array([100,  12])

In [17]:
an_array

array([[11, 12],
       [21, 22],
       [31, 32]])

In [18]:
#filter values which are more than 20 and less than 30
res = (an_array>20)&(an_array<30)
print(res)
a_slice=an_array[res]
print(a_slice)

[[False False]
 [ True  True]
 [False False]]
[21 22]


<h2>Array Operations</h2>
<h4>Arithmetic Array Operations</h4>

In [19]:
x = np.array([[1,2],[3,4]], dtype='int64')
y = np.array([[1.0,2.0],[3.0,4.0]], dtype=np.float64)
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[1. 2.]
 [3. 4.]]


In [20]:
print('Addition : ')
print(x+y)
print('Subtraction : ')
print(x-y)
print('Multiplication : ')
print(x*y)
print('Division : ')
print(x/y)

Addition : 
[[2. 4.]
 [6. 8.]]
Subtraction : 
[[0. 0.]
 [0. 0.]]
Multiplication : 
[[ 1.  4.]
 [ 9. 16.]]
Division : 
[[1. 1.]
 [1. 1.]]


In [21]:
print(np.add(x,y))           # vectorized methods 
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))

[[2. 4.]
 [6. 8.]]
[[0. 0.]
 [0. 0.]]
[[ 1.  4.]
 [ 9. 16.]]
[[1. 1.]
 [1. 1.]]


<h2>Element-Wise Functions</h2>

In [23]:
# random array
np.random.seed(1)
x = np.random.randint(1,8,5)
x

array([6, 4, 5, 1, 2])

In [24]:
# another random array
np.random.seed(2)
y = np.random.randint(1,8,5)
y

array([1, 6, 1, 7, 4])

In [25]:
# returns element wise maximum between two arrays
print(np.maximum(x,y))
# returns element wise minimum between two arrays
print(np.minimum(x,y))
# returns boolean values as a result of equality operation.
print(np.equal(x,y))

[6 6 5 7 4]
[1 4 1 1 2]
[False False False False False]


<h2>Statistical Methods</h2>
<h3>Basic Statistical Operations</h3>

In [27]:
np.random.seed(10)
# setup a random 2 x 5 matrix
arr = np.random.randint(1,10,(2,5))
print(arr)
#dir(np.random)
arr.shape

[[5 1 2 1 2]
 [9 1 9 7 5]]


(2, 5)

In [28]:
#compute the mean for all elements
print(arr.mean())

4.2


In [29]:
#compute the means by row
print(arr.mean(axis=1))

[2.2 6.2]


In [30]:
#compute the means by column
print(arr.mean(axis=0))

[7.  1.  5.5 4.  3.5]


In [31]:
# sum all the elements
print(arr.sum())   # sum of all elements
print('columns sum is : ', arr.sum(axis=0))    # colsum
print('row sum is : ', arr.sum(axis=1))    # row sum

42
columns sum is :  [14  2 11  8  7]
row sum is :  [11 31]


<h2>Finding Unique elements</h2>

In [3]:
array =np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


<h2>Broadcasting</h2>

In [34]:
a1 = np.array([[1,2,3],[4,5,6]])
print('shape of a1 : ',a1.shape)
print('dimension of a1 : ', a1.ndim)
print('array a1:',a1)

shape of a1 :  (2, 3)
dimension of a1 :  2
array a1: [[1 2 3]
 [4 5 6]]


In [35]:
a2 = np.array([1,2,1])
print('shape of a2:',a2.shape)
print('dimension of a2:', a2.ndim)
print('array a2:', a2)

shape of a2: (3,)
dimension of a2: 1
array a2: [1 2 1]


In [36]:
a3=a1+a2
print(a3)

[[2 4 4]
 [5 7 7]]


In [37]:
start =np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
add_cols = np.array([[1],[2],[3],[4]])
print(add_cols)
add_cols.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

In [40]:
start+add_cols

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [44]:
#this will just broadcast in both dimnesions
add_scalar = np.array([5])
print(start+add_scalar)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [45]:
arr = np.ones((3,2))
print(arr.shape)
print(arr)

(3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [46]:
arr2=np.arange(3)
print(arr2.shape)
print(arr2)

(3,)
[0 1 2]


In [47]:
print(arr+arr2)
#broadcast will not happen as dimenions are not corelating

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

<h2>Reshaping array:</h2>

In [5]:
#grab values from 0 through 19 in an array
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [50]:
#reshape to be a 4x5 matrix
new_arr=arr.reshape(4,5)
new_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
#to convert from nD to 1D
new_arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

<h2>Indexing using where():</h2>

In [54]:
x_1=np.array([1,2,3,4,5])
y_1=np.array([11,22,33,44,55])

In [55]:
#gives output by checking condition if condition true returns value from
#x_1 if condition is false value comes from y_1
out=np.where(x_1%2!=0,x_1,y_1)
out

array([ 1, 22,  3, 44,  5])

In [63]:
np.random.seed(1)
mat = np.random.randint(1,10,25)
print(mat.shape)
print(mat.reshape(5,5))

(25,)
[[6 9 6 1 1]
 [2 8 7 3 5]
 [6 3 5 3 5]
 [8 8 2 8 1]
 [7 8 7 2 1]]


In [57]:
np.where(mat > 5, 1000,-1)

array([1000, 1000, 1000,   -1,   -1,   -1, 1000, 1000,   -1,   -1, 1000,
         -1,   -1,   -1,   -1, 1000, 1000,   -1, 1000,   -1, 1000, 1000,
       1000,   -1,   -1])

<h3>"any" or "all" conditions</h3>

In [64]:
arr_bools = np.array([ True, False, True, True, False ])
b1 = np.array([ True, True, True, True, True ])
b2 =  np.array([ False, False, False, False, False ])

In [65]:
print(arr_bools.any())
print(b1.any())
print(b2.any())

True
True
False


In [66]:
print(arr_bools.all())
print(b1.all())
print(b2.all())

False
True
False


<h2>Merging and Spliting data sets</h2>

In [3]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[37  2]
 [34 28]]

[[ 9 41]
 [47 23]]


In [4]:
np.vstack((K,M))

array([[37,  2],
       [34, 28],
       [ 9, 41],
       [47, 23]])

In [5]:
np.hstack((K,M))

array([[37,  2,  9, 41],
       [34, 28, 47, 23]])

In [6]:
np.concatenate([K,M],axis=0)

array([[37,  2],
       [34, 28],
       [ 9, 41],
       [47, 23]])

In [7]:
np.concatenate([K,M],axis=1)

array([[37,  2,  9, 41],
       [34, 28, 47, 23]])

In [8]:
A=np.random.randint(1,21,size=(4,4))
A

array([[ 8, 18, 12, 12],
       [ 5,  3,  5,  2],
       [ 6,  6,  4, 11],
       [ 7, 13,  2,  4]])

In [15]:
B=np.split(A,2,axis=0)
B

[array([[ 8, 18, 12, 12],
        [ 5,  3,  5,  2]]), array([[ 6,  6,  4, 11],
        [ 7, 13,  2,  4]])]

In [17]:
C=np.hsplit(A,2)
C

[array([[ 8, 18],
        [ 5,  3],
        [ 6,  6],
        [ 7, 13]]), array([[12, 12],
        [ 5,  2],
        [ 4, 11],
        [ 2,  4]])]

In [21]:
D=np.vsplit(A,1)
D

[array([[ 8, 18, 12, 12],
        [ 5,  3,  5,  2],
        [ 6,  6,  4, 11],
        [ 7, 13,  2,  4]])]

In [ ]:

Exercise : A store maintains a list of all customers with the customer number and the price of each item purchased by the customer. Find the total amount for each customer.
    

orders = [[1,(100,500.50,450)],[2,(200,300.75,450.50)],[3,(400,300.50,650.50)]]
print(orders)
