In [18]:
from functools import reduce

In [2]:
s1='Python'

print(list(enumerate(s1,2)))

[(2, 'P'), (3, 'y'), (4, 't'), (5, 'h'), (6, 'o'), (7, 'n')]


In [4]:
my_string='I love you'
k = [print(i) for i in my_string if i not in "aeiou"]
k

I
 
l
v
 
y


[None, None, None, None, None, None]

In [5]:
print([i+j for i in "abc" for j in "def"])

['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']


In [6]:
l=[1, 2, 3, 4, 5]

def f1(x):

    return x<0

m1=filter(f1, l)

print(list(m1))

[]


In [23]:
list(filter(lambda x, y: x<0, l))

TypeError: <lambda>() missing 1 required positional argument: 'y'

In [9]:
def to_upper(k):

    k.upper()

x = ['ab', 'cd']

print(list(map(to_upper, x)))

[None, None]


In [10]:
l1=[1,2,3]

l2=[4,5,6]

l3=[7,8,9]

for x, y, z in zip(l1, l2, l3):

	print(x, y, z) 

1 4 7
2 5 8
3 6 9


In [11]:
for i in range(1, 101):

	if int(i*0.5)==i*0.5:

		print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [15]:
[for i in range(1, 101) if int(i*0.5)==(i*0.5) i]

SyntaxError: invalid syntax (<ipython-input-15-4cc3b4c3fb60>, line 1)

In [16]:
f=lambda x:bool(x%2)

print(f(20), f(21))

False True


In [21]:
l=[1, 2, 3, 4, 5]

m=reduce(lambda x, y:x if x>y else y, l)

print(m)

5


In [20]:
list(map((lambda x:x**2), filter((lambda x:x%2==0), range(10))))

[0, 4, 16, 36, 64]

In [24]:
import numpy as np

In [25]:
import matplotlib.pyplot as plt

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/matplotlib/font_manager.py:229: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '


In [27]:
b = np.array([1,2,3])

b[1] = 'one'
b

ValueError: invalid literal for int() with base 10: 'one'

In [31]:
np.array([[11,12,13,21,22,23]])


array([[11, 12, 13, 21, 22, 23]])

In [32]:
arr = np.array([1,2,3,4,5])
arr[4] = 7
arr

array([1, 2, 3, 4, 7])

In [34]:
arr[(arr%2 == 1)]


array([1, 3, 7])

In [35]:
arr[(arr%2 != 1)]

array([2, 4])

In [79]:
A = np.array([[11,12,13],[21,22,23],[31,32,33]])
x=A[:2,:2]
print(x)
x.ndim
x[0,1]='one'

[[11 12]
 [21 22]]


ValueError: invalid literal for int() with base 10: 'one'

In [51]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [78]:
y=A[:1,2]
print(y)
y.ndim


[13]


1

In [55]:
A<20 

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [65]:
A = np.array([[1,2,3],[4,5,6]])

B = np.array([[1,1,1], [2,2,2]])

A+B

array([[2, 3, 4],
       [6, 7, 8]])

In [75]:
A.sum()

21

In [61]:
arr = np.arange(0,40,1)
arr.reshape(6,7)



ValueError: cannot reshape array of size 40 into shape (6,7)

In [62]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

A.mean(axis = 1)

array([2., 5., 8.])

In [67]:
np.random.randint(1,7,20)

array([2, 6, 1, 6, 3, 6, 4, 6, 2, 4, 3, 4, 6, 6, 2, 1, 2, 6, 5, 5])

In [68]:
a = np.array([2,3])

b1 = np.array([1])

b2 = 1

In [70]:
a+b2

array([3, 4])

In [5]:
import pandas as pd
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
print("\nFirst 3 rows of the said DataFrame':")
df1 = df.head(3)
print(df1)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

First 3 rows of the said DataFrame':
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8


In [6]:
import numpy as np
df1.iloc[:2]=np.NaN

In [7]:
print(df1)

   col1  col2  col3
0   NaN   NaN   NaN
1   NaN   NaN   NaN
2   3.0   6.0   8.0


In [14]:
import sklearn.preprocessing as  preprocessing
import sklearn.datasets  as  datasets
import sklearn.preprocessing  as  OneHOtEncoder
import numpy as np
import pandas as pd
iris= datasets.load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [23]:
iris= datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
import numpy as np
df.iloc[:3]=np.NaN
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                NaN               NaN                NaN               NaN
1                NaN               NaN                NaN               NaN
2                NaN               NaN                NaN               NaN
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


In [24]:
import sklearn.preprocessing as  preprocessing

In [ ]:
imputer= preprocessing.imputer()

In [25]:
import sklearn.preprocessing as preprocessing

x = [[0, 0], [0, 1], [2,0]]
enc = preprocessing.OneHotEncoder()
print(enc.fit(x).transform([[1, 1]]).toarray())

[[0. 0. 0. 1.]]


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [26]:
import sklearn.preprocessing as preprocessing

x = [[7.8], [1.3], [4.5], [0.9]]
print(preprocessing.Binarizer().fit(x).transform(x))

[[1.]
 [1.]
 [1.]
 [1.]]


In [27]:
import sklearn.preprocessing as preprocessing

regions = ['HYD', 'CHN', 'MUM', 'HYD', 'KOL', 'CHN']
print(preprocessing.LabelEncoder().fit(regions).transform(regions))

[1 0 3 1 2 0]
