In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score,auc,roc_curve,confusion_matrix, classification_report,roc_auc_score

In [2]:
Heartdata=pd.read_csv('https://storage.googleapis.com/dimensionless/Analytics/framingham.csv')

In [3]:
Heartdata.shape

(4240, 16)

In [4]:
Heartdata.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [5]:
Heartdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
male               4240 non-null int64
age                4240 non-null int64
education          4135 non-null float64
currentSmoker      4240 non-null int64
cigsPerDay         4211 non-null float64
BPMeds             4187 non-null float64
prevalentStroke    4240 non-null int64
prevalentHyp       4240 non-null int64
diabetes           4240 non-null int64
totChol            4190 non-null float64
sysBP              4240 non-null float64
diaBP              4240 non-null float64
BMI                4221 non-null float64
heartRate          4239 non-null float64
glucose            3852 non-null float64
TenYearCHD         4240 non-null int64
dtypes: float64(9), int64(7)
memory usage: 530.1 KB


In [6]:
Heartdata.describe()

male          age    education  currentSmoker   cigsPerDay  \
count  4240.000000  4240.000000  4135.000000    4240.000000  4211.000000   
mean      0.429245    49.580189     1.979444       0.494104     9.005937   
std       0.495027     8.572942     1.019791       0.500024    11.922462   
min       0.000000    32.000000     1.000000       0.000000     0.000000   
25%       0.000000    42.000000     1.000000       0.000000     0.000000   
50%       0.000000    49.000000     2.000000       0.000000     0.000000   
75%       1.000000    56.000000     3.000000       1.000000    20.000000   
max       1.000000    70.000000     4.000000       1.000000    70.000000   

            BPMeds  prevalentStroke  prevalentHyp     diabetes      totChol  \
count  4187.000000      4240.000000   4240.000000  4240.000000  4190.000000   
mean      0.029615         0.005896      0.310613     0.025708   236.699523   
std       0.169544         0.076569      0.462799     0.158280    44.591284   
min       0.000000         0.000000      0.000000     0.000000   107.000000   
25%       0.000000         0.000000      0.000000     0.000000   206.000000   
50%       0.000000         0.000000      0.000000     0.000000   234.000000   
75%       0.000000         0.000000      1.000000     0.000000   263.000000   
max       1.000000         1.000000      1.000000     1.000000   696.000000   

             sysBP        diaBP          BMI    heartRate      glucose  \
count  4240.000000  4240.000000  4221.000000  4239.000000  3852.000000   
mean    132.354599    82.897759    25.800801    75.878981    81.963655   
std      22.033300    11.910394     4.079840    12.025348    23.954335   
min      83.500000    48.000000    15.540000    44.000000    40.000000   
25%     117.000000    75.000000    23.070000    68.000000    71.000000   
50%     128.000000    82.000000    25.400000    75.000000    78.000000   
75%     144.000000    90.000000    28.040000    83.000000    87.000000   
max     295.000000   142.500000    56.800000   143.000000   394.000000   

        TenYearCHD  
count  4240.000000  
mean      0.151887  
std       0.358953  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000

In [7]:
#1. What kind of Machine Learning problems can be solved using Decision Tree Models?
#Ans:d.Both (a) and (b)

In [8]:
#2. For a Regression Tree the predicted value of the regions is calculated as
#Ans: a.Mean of the data points within that region.

In [9]:
#3.For the decision tree model, what is the maximum depth of the tree?
#Ans:3(longest path from root node to terminal)

In [10]:
#4.For the decision tree model, How many terminal nodes are present?
#Ans:8(all leaf nodes)

In [11]:
#5.Identify the number of splits in the decision tree model.
#Ans:7(ternimal nodes-1)

In [12]:
#6. What is the predicted outcome for a person who is 36 years old, smokes 8 cigarettes a day and has a total cholesterol of 479?
#Ans:0

In [13]:
x=(Heartdata.age==36)&(Heartdata.cigsPerDay==8)&(Heartdata.totChol==479)
x.sum()

0

In [14]:
#7.What is the default value for the splitting criteria parameter for Decision Tree Classifier?
#Ans:Gini(Criteria for splitting tree)

In [15]:
#8. Using the Decision Tree Classifier, create a model (name the model as ‘tree_clf’) with the parameter max_depth = 5 on training data. 
#What is the Accuracy score of this model on the test data?
#Ans:c. Accuracy = 0.835

In [16]:
tree_clf=DecisionTreeClassifier(max_depth=5,random_state=100)

In [17]:
Heartdata.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [18]:
Heartdata1=Heartdata
Heartdata1=Heartdata1.dropna()
Heartdata1.shape

(3658, 16)

In [19]:
y = Heartdata1['TenYearCHD']
X = Heartdata1.drop(['TenYearCHD'], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35, random_state = 100,stratify=y)

In [20]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2377, 15), (1281, 15), (2377,), (1281,))

In [21]:
X_train.columns

Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose'],
      dtype='object')

In [22]:
tree_clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [23]:
tree_clf.score(X_train,y_train)

0.8666386201093815

In [24]:
y_pred_train = tree_clf.predict(X_train)

In [25]:
confusion_matrix(y_train, y_pred_train)   

array([[1991,   24],
       [ 293,   69]])

In [26]:
y_pred_test=tree_clf.predict(X_test)

In [27]:
accuracy_score(y_test,y_pred_test)

0.8352849336455894

In [28]:
#9. Implement the Grid Search Cross Validation method to tune the ‘tree_clf’ model by setting the following hyperparameters in the param_grid:
#max_depth: [3, 5, 7, 9],
#Other parameters:
#scoring = ‘accuracy’, cv = 5
#What are the best hyperparameter value for the ‘tree_clf’ model?
#Ans:b. max_depth: 3

In [29]:
parameters = {'max_depth': [3,5,7,9]} 

In [30]:
grid = GridSearchCV(tree_clf,parameters,cv=5,scoring='accuracy')

In [31]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_depth': [3, 5, 7, 9]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring='accuracy',
       verbose=0)

In [32]:
grid.best_params_

{'max_depth': 3}

In [33]:
#10. Implement the Grid Search Cross Validation method to tune the ‘tree_clf’ model by setting the following hyperparameters in the param_grid:
#max_depth: [3, 5, 7, 9],
#Other parameters:
#scoring = ‘accuracy’, cv = 5
#What is the best cross validation score?
#Ans:a. 0.843

In [34]:
grid.best_score_

0.8430795119899033

In [35]:
#11. Use Decision Tree Classifier to create a model (‘tree_clf_pruned’) with the parameter max_depth = 3 on training data.
#What is the Accuracy score of this model on test data?
#Ans:c. Accuracy = 0.842

In [36]:
tree_clf_pruned=DecisionTreeClassifier(max_depth=3,random_state=100)

In [37]:
tree_clf_pruned.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [38]:
tree_clf_pruned.score(X_train,y_train)

0.8510727808161548

In [39]:
y_pred_train_prun = tree_clf_pruned.predict(X_train)

In [40]:
accuracy_score(y_train,y_pred_train_prun)

0.8510727808161548

In [41]:
y_pred_test_prun = tree_clf_pruned.predict(X_test)

In [42]:
accuracy_score(y_test,y_pred_test_prun)

0.8423106947697112

In [43]:
#12. If the objective of the model is to predict most of the patients with CHD (heart disease) correctly, 
#which of the following performance measure will be considered?
#Ans:Sensitivity

In [44]:
#13. Which one of the following is not a hyper-parameter for the Random Forest Classifier?
#Ans:c. learning_rate

In [45]:
#14. Using the Random Forest Classifier, create a model (name it as ‘forest_clf’) with the parameter n_estimators = 500 and random_state = 100 on the training data.
#What is the Accuracy score of this model on the test data?
#Ans:b. Accuracy = 0.848

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
forest_clf = RandomForestClassifier( n_estimators = 500,random_state = 100)
forest_clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=None,
            oob_score=False, random_state=100, verbose=0, warm_start=False)

In [48]:
forest_clf_pred = forest_clf.predict(X_test)

In [49]:
accuracy_score(y_test,forest_clf_pred)

0.8485558157689306

In [50]:
#15. Using the Random Forest Classifier, create a model (name it as ‘forest_clf’) with the parameter n_estimators = 500 and random_state = 100 on the training data. 
#Which of the following variable is the most important feature?
#d. sysBP

In [51]:
forest_clf.feature_importances_

array([0.02153472, 0.12228503, 0.03820032, 0.01283623, 0.0505311 ,
       0.00556871, 0.00361337, 0.01913572, 0.00651401, 0.12146447,
       0.1368072 , 0.11595572, 0.12834315, 0.09531059, 0.12189965])

In [52]:
data = pd.Series(data=forest_clf.feature_importances_,index=X.columns)
data

male               0.021535
age                0.122285
education          0.038200
currentSmoker      0.012836
cigsPerDay         0.050531
BPMeds             0.005569
prevalentStroke    0.003613
prevalentHyp       0.019136
diabetes           0.006514
totChol            0.121464
sysBP              0.136807
diaBP              0.115956
BMI                0.128343
heartRate          0.095311
glucose            0.121900
dtype: float64

In [53]:
#16. Implement the Grid Search Cross Validation method to tune the random forest model (‘forest_clf’) by setting the following hyperparameters in the param_grid
#max_depth: [3, 5, 7]
#max_features: [‘log2’, ‘sqrt’]
#n_estimators: [250, 500, 750]
#Other parameters:
#scoring = ‘accuracy’, cv = 5
#What are the best hyperparameters for the Random Forest Model?
#b. max_depth: 5, max_features: ‘sqrt’, n_estimators: 250

In [54]:
param_grid = {'max_depth': [3, 5, 7], 'max_features':['log2', 'sqrt'],'n_estimators':[250, 500, 750]}

In [55]:
grid_search = GridSearchCV(forest_clf,param_grid,cv=5,scoring='accuracy')

In [56]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=None,
            oob_score=False, random_state=100, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_depth': [3, 5, 7], 'max_features': ['log2', 'sqrt'], 'n_estimators': [250, 500, 750]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [57]:
grid_search.best_params_

{'max_depth': 5, 'max_features': 'log2', 'n_estimators': 250}

In [58]:
#17. The following graph was plotted which shows the Accuracy, Sensitivity and Specificity for a range of probability threshold.
#What is the approximate optimum value for threshold from the above graph?
#Ans:d. 0.4

In [ ]:
#18. In Gradient Boosting Classifier, how are the decision trees (weak learners) are generated?
#Ans: a. The trees are generated sequentially

In [ ]:
#19. The three hyper-parameters for Boosting are:
#Ans: b. Number of Trees, Learning rate, Depth of tree.

In [ ]:
#20. Using the Gradient Boosting Classifier, instantiate two classification models with the following parameters
#Model 1: n_estimators = 1000, learning_rate = 0.1
#Model 2: n_estimators = 500, learning_rate = 1
#Which model is a better with respect to the Accuracy on test data?
#Ans:a. Model 1

In [59]:
!pip install xgboost

     |████████████████████████████████| 142.8MB 4.3kB/s eta 0:00:01    |████▌                           | 20.3MB 4.2MB/s eta 0:00:30     |█████                           | 22.3MB 4.2MB/s eta 0:00:29     |███████▋                        | 34.1MB 8.3MB/s eta 0:00:14     |█████████                       | 40.1MB 946kB/s eta 0:01:49     |██████████▎                     | 46.0MB 946kB/s eta 0:01:43     |████████████████████████▌       | 109.5MB 1.0MB/s eta 0:00:33██████▊       | 110.3MB 1.0MB/s eta 0:00:32     |███████████████████████████▍    | 122.4MB 4.3MB/s eta 0:00:05   | 123.8MB 4.3MB/s eta 0:00:05��█████████▍   | 126.7MB 6.0MB/s eta 0:00:03��█████████▋   | 127.7MB 6.0MB/s eta 0:00:03��██████████   | 129.4MB 6.0MB/s eta 0:00:03��████████████████████▎  | 130.9MB 6.0MB/s eta 0:00:02��████████████████████▋  | 132.4MB 443kB/s eta 0:00:24��█████████████████████  | 133.7MB 443kB/s eta 0:00:21    |██████████████████████████████▎ | 134.9MB 443kB/s eta 0:00:18    |██████████████████████████████

In [60]:
import xgboost as xgb
from xgboost.sklearn import XGBClassifier

In [68]:
model_xgb1 =  XGBClassifier(n_estimators=500,learning_rate=1)

In [69]:
model_xgb1.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=500, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [70]:
model_xgb1.score(X_train,y_train)

1.0

In [71]:
y_pred_xgb1 = model_xgb1.predict(X_test)

In [72]:
confusion_matrix(y_test,y_pred_xgb1)

array([[1000,   86],
       [ 160,   35]])

In [73]:
accuracy_score(y_test,y_pred_xgb1)

0.8079625292740047

In [67]:
model_xgb2 =  XGBClassifier(n_estimators=1000,learning_rate=0.1)

In [74]:
model_xgb2.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=1000, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [75]:
model_xgb2.score(X_train,y_train)

0.9734960033655868

In [76]:
y_pred_xgb2 = model_xgb2.predict(X_test)

In [77]:
confusion_matrix(y_test,y_pred_xgb2)

array([[1034,   52],
       [ 174,   21]])

In [78]:
accuracy_score(y_test,y_pred_xgb2)

0.8235753317720531